name: Build-LEDE

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      WORKDIR: /mnt/lede
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_NAME: lede
      SSH_ENABLE: false

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build space
      run: |
        sudo mkdir -p $WORKDIR
        sudo chown $USER:$USER $WORKDIR
        df -h

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
        gettext git libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone Source
      working-directory: /mnt
      run: |
        git clone $REPO_URL $REPO_NAME
        cd $REPO_NAME
        df -h

    - name: (Optional) SSH Debug
      if: env.SSH_ENABLE == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Run first custom script (after clone)
      run: |
        FILE1=$(ls -1 lede*.sh | sed -n '1p' || true)
        if [ -f "$FILE1" ]; then
          chmod +x "$FILE1"
          ./"$FILE1"
        fi

    - name: Put .config
      run: |
        if [ -f "lede.config" ]; then
          cp lede.config /mnt/lede/.config
        fi

    - name: Feeds
      working-directory: /mnt/lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run second custom script (after feeds)
      run: |
        FILE2=$(ls -1 lede*.sh | sed -n '2p' || true)
        if [ -f "$FILE2" ]; then
          chmod +x "$FILE2"
          ./"$FILE2"
        fi

    - name: Compile
      working-directory: /mnt/lede
      run: |
        make defconfig
        make -j$(nproc) || make -j1 V=s

    - name: Package bin folder
      working-directory: /mnt/lede
      run: |
        cd bin
        zip -r ../lede_bin.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lede_bin
        path: /mnt/lede/lede_bin.zip

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: /mnt/lede/lede_bin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
