name: Build LEDE

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH'
        required: false
        default: 'false'
  schedule:
    - cron: '0 0 3 * *'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_NAME: lede
  WORKDIR: /mnt/lede
  CCACHE_DIR: /mnt/ccache_lede
  CCACHE_MAXSIZE: 10G
  SSH_ENABLE: ${{ github.event.inputs.ssh || 'false' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: |
          sudo apt update
          sudo apt install -y bc lm-sensors pciutils wsdd2 ccache
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
          genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
          libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
          libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf \
          python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
          swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Prepare workspace
        run: |
          sudo mkdir -p /mnt
          sudo chown $USER:$USER /mnt

      - name: Clone source
        run: |
          git clone --depth=1 $REPO_URL $WORKDIR

      - name: Run first script (add packages)
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '1p')
          chmod +x "$FILE"
          "$FILE"

      
      - name: Feeds update
        run: |
          cd $WORKDIR
          ./scripts/feeds update -a
          ./scripts/feeds install -a


      - name: Copy config
        run: |
          mv $GITHUB_WORKSPACE/lede/.config $WORKDIR/.config   

      

      - name: Run second script
        run: |
          cd $WORKDIR
          FILE=$(ls $GITHUB_WORKSPACE/lede/lede*.sh | sed -n '2p')
          chmod +x "$FILE"
          "$FILE"


      - name: download
        run: |
          cd $WORKDIR
          make download -j$(nproc) || make download -j8

      - name: Prepare config
        run: |
          cd $WORKDIR
          make clean
          make defconfig 
          chmod +x $GITHUB_WORKSPACE/check-packages-status.sh
          bash $GITHUB_WORKSPACE/check-packages-status.sh
          chmod +x $GITHUB_WORKSPACE/auto-fix-packages.sh
          #####删除注释恢复运行#####
          #bash $GITHUB_WORKSPACE/auto-fix-packages.sh

      - name: Compile
        run: |
          cd $WORKDIR
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR=$CCACHE_DIR
          ccache -M $CCACHE_MAXSIZE
          make -j$(nproc) || make -j1 V=s

      - name: Package bin
        run: |
          cd $WORKDIR
          zip -r lede_bin.zip bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lede_bin
          path: ${{ env.WORKDIR }}/lede_bin.zip

      - name: Create tag
        run: |
          TAG=$(date +"lede-%Y%m%d-%H%M")
          git tag -f "$TAG"
          git push -f origin "$TAG"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.WORKDIR }}/lede_bin.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
