name: Build-LEDE

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      WORKDIR: /mnt/lede
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_NAME: lede
      SSH_ENABLE: false
      CCACHE_DIR: /mnt/ccache_lede
      CCACHE_MAXSIZE: 10G

    steps:
    - uses: actions/checkout@v4

    - name: Prepare
      run: |
        sudo mkdir -p $WORKDIR $CCACHE_DIR
        sudo chown -R $USER:$USER /mnt
        df -h

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
        gettext git libssl-dev python3 python3-pip python3-venv rsync unzip zlib1g-dev \
        file wget ccache

    - name: Enable ccache
      run: |
        echo 'export CC="ccache gcc"' >> ~/.bashrc
        echo 'export CXX="ccache g++"' >> ~/.bashrc
        echo 'export CCACHE_DIR=$CCACHE_DIR' >> ~/.bashrc
        source ~/.bashrc
        ccache -M $CCACHE_MAXSIZE
        ccache -s

    - name: Restore ccache
      uses: actions/cache@v4
      with:
        path: /mnt/ccache_lede
        key: ccache-lede-${{ github.ref }}
        restore-keys: |
          ccache-lede-

    - name: Clone Source
      working-directory: /mnt
      run: |
        git clone $REPO_URL $REPO_NAME

    - name: SSH (optional)
      if: env.SSH_ENABLE == 'true'
      uses: mxschmitt/action-tmate@v3

    - name: Run first custom script
      working-directory: /mnt/lede
      run: |
        FILE=$(ls -1 $GITHUB_WORKSPACE/lede*.sh | sed -n '1p' || true)
        [ -f "$FILE" ] && chmod +x "$FILE" && "$FILE"

    - name: Put .config
      run: |
        [ -f "lede.config" ] && cp lede.config /mnt/lede/.config

    - name: Feeds
      working-directory: /mnt/lede
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Run second custom script
      working-directory: /mnt/lede
      run: |
        FILE=$(ls -1 $GITHUB_WORKSPACE/lede*.sh | sed -n '2p' || true)
        [ -f "$FILE" ] && chmod +x "$FILE" && "$FILE"

    - name: Build
      working-directory: /mnt/lede
      run: |
        make defconfig
        make -j$(nproc) || make -j1 V=s
        ccache -s

    - name: Pack
      working-directory: /mnt/lede
      run: |
        cd bin
        zip -r ../lede_bin.zip .

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lede_bin
        path: /mnt/lede/lede_bin.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: /mnt/lede/lede_bin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
